name: Sphinx Documentation

on:
  push:
    branches:
      - main
    tags-ignore:
      - '**'
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_dispatch:

jobs:
  doc-tests:
    name: Documentation Tests
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repository Files
        uses: actions/checkout@v3

      - name: Run Setup Action
        uses: ./.github/workflows/composite-actions/setup
        with:
          python-version: '3.8'
          pip-requirements-file: docs/requirements.txt

      - name: Build Documentation
        if: ${{ always() }}
        run: |
          cd $GITHUB_WORKSPACE/docs
          SPHINXOPTS="-W" make html

      - name: Run Spell-Checking
        if: ${{ always() }}
        run: |
          cd $GITHUB_WORKSPACE/docs
          SPHINXOPTS="-W" make spelling
