name: Security Analysis Scanning

on:
  push:
    branches:
      - main
    tags-ignore:
      - '**'
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_dispatch:

jobs:
  setup:
    name: Set up Job Configuration
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Check Out Repository Files
        uses: actions/checkout@v3

      - name: Run Setup Action
        uses: ./.github/workflows/composite-actions/load-workflow-config

      - name: Set up Python Version Matrix
        id: set-matrix
        run: echo "::set-output name=matrix::${{ env.PYTHON_VERSIONS }}"

  bandit:
    name: Bandit Scan (Python ${{ matrix.python-version }})
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.setup.outputs.matrix) }}
    steps:
      - name: Check Out Repository Files
        uses: actions/checkout@v3

      - name: Run Setup Action
        uses: ./.github/workflows/composite-actions/setup
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run Security Analysis Scan
        run: bandit -rv "${{ env.PACKAGE_NAME }}"
